# INPUT PATHS
active_dataset: BSD10k-v1.2
datasets:
  BSD10k-v1.2:
    metadata_csv: "C:/Users/solok/Desktop/Dcase baseline/data/metadata/BSD10k_metadata.csv"
    audio_emb_folder: "C:/Users/solok/Desktop/Dcase baseline/data/features/clap_audio_embeddings"
    text_emb_folder: "C:/Users/solok/Desktop/Dcase baseline/data/features/clap_text_embeddings"
    class_names: "C:/Users/solok/Desktop/Dcase baseline/data/metadata/BST_description.csv"

  BSD35k-CS:
    metadata_csv: "C:/Users/solok/Desktop/Dcase baseline/data/metadata/BSD35k-CS_metadata.csv"
    audio_emb_folder: "C:/Users/solok/Desktop/Dcase baseline/data/features/clap_audio_embeddings"
    text_emb_folder: "C:/Users/solok/Desktop/Dcase baseline/data/features/clap_text_embeddings"
    class_names: "C:/Users/solok/Desktop/Dcase baseline/data/metadata/BST_description.csv"

# OUTPUT PATHS
output_path: "data"
processed_dataset_csv: "processed_dataset.csv"
class_dict_json: "class_dict.json"
top_class_dict_json: "top_class_dict.json"
top_class_subclass_dict_json: "top_class_subclass_dict.json"
